// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: inventory/v1/inventory.proto

package inventoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	InventoryService_GetStock_FullMethodName   = "/inventory.v1.InventoryService/GetStock"
	InventoryService_Reserve_FullMethodName    = "/inventory.v1.InventoryService/Reserve"
	InventoryService_Release_FullMethodName    = "/inventory.v1.InventoryService/Release"
	InventoryService_WatchStock_FullMethodName = "/inventory.v1.InventoryService/WatchStock"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventoryService — складской сервис.
//
// Почему gRPC, а не REST, для этого взаимодействия:
//   - контракт описан в .proto и проверяется компилятором на обеих сторонах;
//   - protobuf компактнее и быстрее JSON при парсинге;
//   - HTTP/2 даёт мультиплексирование в одном TCP-соединении, поэтому
//     нет накладных расходов на установку соединения под каждый вызов;
//   - из коробки есть server-streaming, дедлайны и коды ошибок.
type InventoryServiceClient interface {
	// GetStock — остаток по одному товару (unary RPC).
	GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error)
	// Reserve — атомарно резервирует позиции заказа.
	// Либо резервируются все позиции, либо ни одна (см. OUT_OF_STOCK).
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error)
	// Release — возвращает резерв на склад (компенсирующая операция,
	// вызывается, если заказ не удалось сохранить).
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	// WatchStock — server-streaming: сервер шлёт обновления остатков,
	// пока клиент не закроет поток или не истечёт дедлайн.
	WatchStock(ctx context.Context, in *WatchStockRequest, opts ...grpc.CallOption) (InventoryService_WatchStockClient, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveResponse)
	err := c.cc.Invoke(ctx, InventoryService_Reserve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, InventoryService_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) WatchStock(ctx context.Context, in *WatchStockRequest, opts ...grpc.CallOption) (InventoryService_WatchStockClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InventoryService_ServiceDesc.Streams[0], InventoryService_WatchStock_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &inventoryServiceWatchStockClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InventoryService_WatchStockClient interface {
	Recv() (*StockUpdate, error)
	grpc.ClientStream
}

type inventoryServiceWatchStockClient struct {
	grpc.ClientStream
}

func (x *inventoryServiceWatchStockClient) Recv() (*StockUpdate, error) {
	m := new(StockUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility
//
// InventoryService — складской сервис.
//
// Почему gRPC, а не REST, для этого взаимодействия:
//   - контракт описан в .proto и проверяется компилятором на обеих сторонах;
//   - protobuf компактнее и быстрее JSON при парсинге;
//   - HTTP/2 даёт мультиплексирование в одном TCP-соединении, поэтому
//     нет накладных расходов на установку соединения под каждый вызов;
//   - из коробки есть server-streaming, дедлайны и коды ошибок.
type InventoryServiceServer interface {
	// GetStock — остаток по одному товару (unary RPC).
	GetStock(context.Context, *GetStockRequest) (*GetStockResponse, error)
	// Reserve — атомарно резервирует позиции заказа.
	// Либо резервируются все позиции, либо ни одна (см. OUT_OF_STOCK).
	Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error)
	// Release — возвращает резерв на склад (компенсирующая операция,
	// вызывается, если заказ не удалось сохранить).
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	// WatchStock — server-streaming: сервер шлёт обновления остатков,
	// пока клиент не закроет поток или не истечёт дедлайн.
	WatchStock(*WatchStockRequest, InventoryService_WatchStockServer) error
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInventoryServiceServer struct {
}

func (UnimplementedInventoryServiceServer) GetStock(context.Context, *GetStockRequest) (*GetStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStock not implemented")
}
func (UnimplementedInventoryServiceServer) Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reserve not implemented")
}
func (UnimplementedInventoryServiceServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedInventoryServiceServer) WatchStock(*WatchStockRequest, InventoryService_WatchStockServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchStock not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_GetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetStock(ctx, req.(*GetStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_Reserve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_WatchStock_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchStockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InventoryServiceServer).WatchStock(m, &inventoryServiceWatchStockServer{ServerStream: stream})
}

type InventoryService_WatchStockServer interface {
	Send(*StockUpdate) error
	grpc.ServerStream
}

type inventoryServiceWatchStockServer struct {
	grpc.ServerStream
}

func (x *inventoryServiceWatchStockServer) Send(m *StockUpdate) error {
	return x.ServerStream.SendMsg(m)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStock",
			Handler:    _InventoryService_GetStock_Handler,
		},
		{
			MethodName: "Reserve",
			Handler:    _InventoryService_Reserve_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _InventoryService_Release_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchStock",
			Handler:       _InventoryService_WatchStock_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "inventory/v1/inventory.proto",
}
